class Config:
    
    # Basics
    SEG_DURATION = 1.0
    CHUNK_DURATION = 0.2
    CHUNK_IN_SEG = SEG_DURATION/CHUNK_DURATION
    BITRATE = [2.5, 4.0, 5.0, 6.5, 8.0, 10.0]
    SPEED = [0.9, 1.0, 1.1]
    MAX_RATE = BITRATE[-1]
    FPS = 24
    FRAME_DURATION = 1 / 24
    
    # clients
    INITIAL_DUMMY_LATENCY = 3.0
    INITIAL_RATE = BITRATE[int(len(BITRATE) / 2)]
    INITIAL_LATENCY = 1.5
    CLIENT_MAX_BUFFER_LEN = 5
    MAX_HISTORY = 600
    
    # server
    ENCODING_TIME = 1
    PUSEDO_ENCODE_TIME = ENCODING_TIME
    SERVER_MAX_BUFFER_LEN = 5
    SERVER_ALGO_BUFFER_LEN = 20
    SERVER_ESTIMATION_LEN = 10
    SEG_NUM = 10
    SUGGESTIONS = (-1, 0, 1)
    
    VIDEO_FORMAT = ".mp4"